### ISSUE TITLE
Addition of tests that compare hgvs to vcf translation between this and Ensembl Variant Recoder

### ISSUE THREAD

**Issue by h-joshi** [kidsneuro-lab/hgvs#18]
Persist pre-computed variant recoder output using http://asia.ensembl.org/Homo_sapiens/Tools/VR for `hgvs_vcf_valid.tsv` and `hgvs_vcf_invalid.tsv`

**Comment by PeterKnealeCMRI** [comment]
@h-joshi I didnt do the invalid ones as I presume they would all fail to decode properly?

**Comment by h-joshi** [comment]
> @h-joshi I didnt do the invalid ones as I presume they would all fail to decode properly?

Yup they should all fail to decode
